### ISSUE TITLE
AttributeError: 'ProgressManager' object has no attribute '_shown'

### ISSUE THREAD

**Issue by aaaaaad333** [zefanja/bible-memorizer#1]
I get this error every time I start Anki after installing the addon:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-22 01:07:50
Add-ons possibly involved: ⁨Bible Memorizer⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "/home/username/.local/share/Anki2/addons21/2012700632/model.py", line 140, in <lambda>
    lambda: aqt.mw.progress.update(
  File "aqt.progress", line 214, in update
AttributeError: 'ProgressManager' object has no attribute '_shown'
```

Whenever I sync my collection I also get a popup window saying this even though I made no changes to my decks:

> Your decks here and on AnkiWeb differ in such a way that they can't be merged together, so it's necessary to overwrite the decks on one side with the decks from the other.
> 
> If you choose download, Anki will fetch the collection from AnkiWeb, and any changes you have made on this device since the last sync will be lost.
> 
> If you choose upload, Anki will send this device's data to AnkiWeb, and any changes that are waiting on AnkiWeb will be lost.
> 
> After all devices are in sync, future reviews and added cards can be merged automatically.

**Comment by zefanja** [comment]
> Whenever I sync my collection I also get a popup window saying this even though I made no changes to my decks:

I've updated the note type so you need to sync once in one direction (Anki → Ankiweb, choose upload; make sure you have a backup).
